services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:${GITLAB_VERSION}
    restart: always
    hostname: gitlab

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}

    ports:
      - '${GITLAB_HTTP_PORT}:14080'
      - '${GITLAB_SSH_PORT}:22'

    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'

    shm_size: '${GITLAB_SHM_SIZE}'
